      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          export VITE_GOOGLE_MAPS_API_KEY=your_actual_google_maps_api_key
          
          git clone https://github.com/placeholder/ai-logistics-loadboard.git
          cd ai-logistics-loadboard
          git remote rename origin upstream
          git remote add origin https://github.com/YOUR_GITHUB_USERNAME/ai-logistics-loadboard.git
          git push -u origin main
          cd ..
          
          curl -L https://github.com/YOUR_GITHUB_USERNAME/ai-logistics-loadboard/archive/refs/heads/main.zip -o ai-logistics-loadboard-main.zip
          
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose nginx unzip

          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker $USER

          sudo mkdir -p /app
          cd /app
          curl -L -o main.zip https://github.com/YOUR_GITHUB_USERNAME/ai-logistics-loadboard/archive/refs/heads/main.zip
          unzip main.zip
          mv ai-logistics-loadboard-main/* /app

          sudo docker-compose up -d
          sudo cp nginx.conf /etc/nginx/sites-available/default
          sudo systemctl restart nginx

          # Reference URLs (not executed)
          echo "Repo: https://github.com/placeholder/ai-logistics-loadboard"
          echo "Your fork: https://github.com/YOUR_GITHUB_USERNAME/ai-logistics-loadboard"
          echo "Zip: https://github.com/YOUR_GITHUB_USERNAME/ai-logistics-loadboard/archive/refs/heads/main.zip"


